# Generated by Django 2.0 on 2018-06-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_medicalrecord_diagnosis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='pat_id',
            new_name='patient',
        ),
    ]
