# Generated by Django 2.0 on 2018-06-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20180612_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='aadhar_number',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=1),
        ),
    ]
